#version: "3"
services:
  mysql:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    container_name: project-project
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    image: project-api:v1
    ports:
      - "8000:80"
    env_file:
      - env/.env
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: